"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>ValueError: setting an array element with a sequence. // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not accidentally trigger a request to /favicon.ico which might
         change the application's state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140589323702176,
          CONSOLE_MODE = false,
          EVALEX = false,
          EVALEX_TRUSTED = true,
          SECRET = "None";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>ValueError</h1>
<div class="detail">
  <p class="errormsg">ValueError: setting an array element with a sequence.</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul>
<li><div class="exc-divider">The above exception was the direct cause of the following exception:</div>
<li><div class="frame" id="frame-140589323704192">
  <h4>File <cite class="filename">"/Users/ti/Sites/GitHub/Dash_websites/Dash_USAID/Dash_ODE_SDR_simple.py"</cite>,
      line <em class="line">395</em>,
      in <code class="function">calc_y</code></h4>
  <div class="source "><pre class="line before"><span class="ws">        </span>for k in range(3):</pre>
<pre class="line before"><span class="ws">            </span>if deliveries_t[k] &gt; 0:</pre>
<pre class="line before"><span class="ws">                </span>neg_health_outcomes[k] = neg_HO_t[k] / deliveries_t[k]</pre>
<pre class="line before"><span class="ws">            </span>else:</pre>
<pre class="line before"><span class="ws">                </span>neg_health_outcomes[k] = 0</pre>
<pre class="line current"><span class="ws">            </span>L_health_outcomes[k] = 1 - neg_health_outcomes</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>P_D[t+1]   = L2_4_health_outcomes</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>prob_l4, prob_l2, logit_health_l4, logit_health_l2, logit_health_l4_l2, logit_health_l0 = \</pre>
<pre class="line after"><span class="ws">            </span>get_prob_logit_health(B, l4_quality, l2_quality, neg_health_outcomes, B[&#x27;Health_const_0&#x27;])</pre></div>
</div>
</ul>
  <blockquote>ValueError: setting an array element with a sequence.</blockquote>
</div>

<div class="plain">
    <p>
      This is the Copy/Paste friendly version of the traceback.
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/Users/ti/Sites/GitHub/Dash_websites/Dash_USAID/Dash_ODE_SDR_simple.py&quot;, line 395, in calc_y
    L_health_outcomes[k] = 1 - neg_health_outcomes
ValueError: setting an array element with a sequence.</textarea>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ti/Sites/GitHub/Dash_websites/Dash_USAID/Dash_ODE_SDR_simple.py", line 395, in calc_y
    L_health_outcomes[k] = 1 - neg_health_outcomes
ValueError: setting an array element with a sequence.

-->
